# Generated by Django 2.1.4 on 2018-12-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.TextField(help_text='歌曲', max_length=300, verbose_name='歌曲')),
                ('singer', models.CharField(help_text='歌手', max_length=100, verbose_name='歌手')),
                ('last_modify_date', models.DateTimeField(auto_now=True, help_text='最后修改日期', verbose_name='最后修改时间')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
                'db_table': 'music',
            },
        ),
    ]
